/**
 * Direct-sequence spread-spectrum (DS-SS) building blocks.
 * Proakis & Salehi §10.3 (Spread-Spectrum Communication Systems).
 */

import { qfunc } from '@/lib/dsp/math';

/**
 * Maximal-length sequence (m-sequence) of period N = 2^n - 1, generated by a
 * Fibonacci LFSR with a primitive feedback polynomial. Returned as ±1 chips
 * (logical 1 → +1, logical 0 → -1). Proakis §10.3.5. Supported n: 3..7.
 */
export function mSequence(n: number): number[] {
  // Primitive-polynomial tap positions (1-indexed register stages), per n.
  const TAPS: Record<number, number[]> = {
    3: [3, 1],
    4: [4, 1],
    5: [5, 2],
    6: [6, 1],
    7: [7, 1],
  };
  const taps = TAPS[n];
  if (!taps) throw new Error(`mSequence: unsupported register length n=${n} (use 3..7)`);
  const N = (1 << n) - 1;
  const reg = new Array<number>(n).fill(0);
  reg[0] = 1; // any non-zero initial state
  const out: number[] = [];
  for (let i = 0; i < N; i++) {
    out.push(reg[n - 1] === 1 ? 1 : -1);
    let fb = 0;
    for (const tp of taps) fb ^= reg[tp - 1];
    for (let j = n - 1; j > 0; j--) reg[j] = reg[j - 1];
    reg[0] = fb;
  }
  return out;
}

/**
 * Cyclic (periodic) autocorrelation of a ±1 PN sequence:
 *   R(k) = Σ_i c_i · c_{(i+k) mod N}.
 * For an m-sequence this is two-valued: R(0) = N and R(k≠0) = -1.
 */
export function pnAutocorrelation(seq: number[]): number[] {
  const N = seq.length;
  const ac = new Array<number>(N).fill(0);
  for (let k = 0; k < N; k++) {
    let sum = 0;
    for (let i = 0; i < N; i++) sum += seq[i] * seq[(i + k) % N];
    ac[k] = sum;
  }
  return ac;
}

/**
 * Spread a sequence of ±1 data bits by a ±1 PN code: each bit multiplies the
 * full PN period, producing `bits.length * pn.length` chips. Proakis §10.3.2.
 */
export function spreadBits(bits: number[], pn: number[]): number[] {
  const chips: number[] = [];
  for (const b of bits) for (const c of pn) chips.push(b * c);
  return chips;
}

/**
 * Despread a ±1 chip stream with the same PN code: correlate each PN-length
 * block against the code and decide the bit by the sign of the correlation.
 * Proakis §10.3.2.
 */
export function despreadChips(chips: number[], pn: number[]): number[] {
  const N = pn.length;
  const bits: number[] = [];
  for (let b = 0; b < chips.length / N; b++) {
    let corr = 0;
    for (let i = 0; i < N; i++) corr += chips[b * N + i] * pn[i];
    bits.push(corr >= 0 ? 1 : -1);
  }
  return bits;
}

/** Processing gain in dB: G_p = 10·log10(N), N = chips per bit. Proakis §10.3.2. */
export function processingGainDb(N: number): number {
  return 10 * Math.log10(N);
}

/**
 * Bit-error probability of DS-SS BPSK against a broadband jammer. The despread
 * jammer contributes an equivalent noise floor reduced by the processing gain N:
 *   1/γ_eff = 1/γ_b + JSR/G_p,   P_b = Q(√(2 γ_eff)),
 * where γ_b = E_b/N_0 (linear), JSR is the jammer-to-signal power ratio (linear),
 * and G_p = N. JSR → 0 recovers AWGN BPSK Q(√(2γ_b)). Proakis §10.3.2.
 */
export function dsssBer(ebN0Db: number, jsrDb: number, N: number): number {
  const gb = 10 ** (ebN0Db / 10);
  const jsr = 10 ** (jsrDb / 10);
  const invGammaEff = 1 / gb + jsr / N;
  const gammaEff = 1 / invGammaEff;
  return qfunc(Math.sqrt(2 * gammaEff));
}

/**
 * Probability of error at the correlation detector of a DS-SS BPSK receiver.
 * After despreading, the jammer power is suppressed by the processing gain N, so
 * the detector sees an effective SNR γ_eff and decides with P_e = Q(√(2 γ_eff)).
 * Numerically identical to {@link dsssBer}; named for the detector-output framing
 * of Proakis & Salehi §15.2.2 (Probability of Error at the Detector), p.831.
 */
export function dsssDetectorPe(ebN0Db: number, jsrDb: number, N: number): number {
  return dsssBer(ebN0Db, jsrDb, N);
}
